version: "3.8"
services: 
    web:
        image: "eboraas/laravel"
        command: php /src/app/artisan serve --host 0.0.0.0 --port 8000
        working_dir: "/src/app"
        volumes: 
            - "./src:/src"
        ports: 
            - "8080:8000"
